spark.master                           local[*]
spark.driver.memory                    2g
spark.sql.catalogImplementation       hive
spark.sql.extensions                  org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg             org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type        hive
spark.sql.catalog.iceberg.uri         thrift://localhost:9083
spark.sql.catalog.iceberg.warehouse   hdfs://localhost:9820/warehouse
spark.sql.catalog.spark_catalog       org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type  hive
spark.sql.warehouse.dir               hdfs://localhost:9820/warehouse
spark.hadoop.fs.defaultFS             hdfs://localhost:9820
spark.hadoop.hive.metastore.uris      thrift://localhost:9083
spark.jars                            /opt/spark/extra-jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar,/opt/spark/extra-jars/iceberg-hive-runtime-1.6.1.jar
spark.driver.extraClassPath           /opt/spark/extra-jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar:/opt/spark/extra-jars/iceberg-hive-runtime-1.6.1.jar
spark.executor.extraClassPath         /opt/spark/extra-jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar:/opt/spark/extra-jars/iceberg-hive-runtime-1.6.1.jar
spark.driver.bindAddress              0.0.0.0
spark.driver.host                     127.0.0.1
spark.ui.port                         4040
