spark.master                          local[*]
spark.driver.memory                   2g
spark.sql.catalogImplementation      hive
spark.sql.extensions                 org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.ozone              org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.ozone.type         hadoop
spark.sql.catalog.ozone.warehouse    ofs://om/spark/warehouse
spark.sql.warehouse.dir              file:/data/spark/local-warehouse
spark.hadoop.fs.ofs.impl             org.apache.hadoop.fs.ozone.RootedOzoneFileSystem
spark.hadoop.ozone.om.address        om:9862
spark.hadoop.ozone.replication       1
spark.hadoop.ozone.replication.type  RATIS
spark.driver.bindAddress             0.0.0.0
spark.driver.host                    127.0.0.1
spark.ui.port                        4040
